processing:
  autocontrast: false
  high_quality: false
  font_aspect: 0.45
features:
  color: false
  borders: false
  border_char: '#'
github:
  width: 90
  lock_aspect: true
  char_set: default
output:
  width: 60
  char_set: default
  save_to_file: true
  filename: output.txt
